version: "3.5"

networks:
  # Create an explicit network so we can connect to it from the client to do node deployments.
  # Create it externally so when we remove individual nodes it doesn't try to destroy it.
  p2p-net:
    external: true

# Base template for nodes. Can't use replicas unfortunately because we have to pair them
# with an execution engine. Alternatively we could build a single image.

services:
  # For repeating configs, we could use extension fields: https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd
  # or docker-compose.override.yml as described in https://docs.docker.com/compose/extends/

  # Not going to expose ports on the host because there will be many nodes.
  # We can use a docker container to run the client and connect to the right casperlabs network
  # and pick one particular node.

  node:
    image: ${NODE_NAME}
    container_name: ${NODE_NAME}
    hostname: ${NODE_NAME}
    ports:
      # Port for websocket messages
      - ${NODE_PORT}:8080
    env_file:
      - .env
    entrypoint: node
    command:  peer.js ${BOOTSTRAP_HOSTNAMES}
    networks:
      - p2p-net

